--- #YAML:1.0
name:               Acme-SafetyGoggles
version:            0.04
abstract:           Protects programmer's eyes from source filtering
author:
    - Marty O'Brien <mob@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Filter::Simple:      0
    Filter::Util::Call:  0
    Test::More:          0
no_index:
    directory:
        - t
        - inc
    package:
        - Filter::Simple
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
